version: "3"
services:
  sc-redis:
    image: ${REDIS_IMAGE_NAME}
    container_name: ${REDIS_CONTAINER_NAME}
    environment:
      REDIS_PASS: ${REDIS_PASS}
    volumes:
      - ${REDIS_DB_PATH}:/data
      - ${REDIS_PATH_TO_CERTS}:/certs
    ports:
      - "0.0.0.0:${REDIS_EXTERIOR_PORT}:${REDIS_INTERIOR_PORT}"
    restart: on-failure

  sc-db:
    container_name: ${DB_CONTAINER_NAME}
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    image: ${SCAPI_POSTGRES_IMAGE}
    environment:
      ALLOW_IP_RANGE: 0.0.0.0/0
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_DB: ${POSTGRES_DBNAME}
      # POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology,postgis_raster,pgrouting
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/12/main
      - ${POSTGRES_SSL_PATH}/cert.pem:/var/lib/postgresql/server.crt
      - ${POSTGRES_SSL_PATH}/key.pem:/var/lib/postgresql/server.key
      # - ./db/postgres/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "0.0.0.0:${PG_EXTERIOR_PORT}:${POSTGRES_PORT}"
    restart: on-failure
    healthcheck:
      test: "exit 0"

  sc-api:
    image: ${SCAPI_IMAGE}
    expose:
      - 80
    depends_on:
      - sc-redis
      - sc-db
    container_name: ${API_CONTAINER_NAME}
    volumes:
      - ${REDIS_PATH_TO_CERTS}:/app/certs
    environment:
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_KEYSIZE: ${LETSENCRYPT_KEYSIZE}
      PORT: ${VIRTUAL_PORT}
      GRAPHQL_ENDPOINT: ${GRAPHQL_ENDPOINT}
      SESSION_SECRET: ${SESSION_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_INTERIOR_PORT: ${REDIS_INTERIOR_PORT}
      PG_DB_HOST: ${PG_DB_HOST}
      PG_DB_PORT: ${PG_DB_PORT}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_DB: ${POSTGRES_DBNAME}
      TYPEORM_SYNCHRONIZE: "false"
      TYPEORM_LOGGING: "false"
      PRODUCTION_CLIENT_ORIGIN: ${PRODUCTION_CLIENT_ORIGIN}
      PRODUCTION_API_ORIGIN: ${PRODUCTION_API_ORIGIN}
      PRODUCTION_CLIENT_URI: ${PRODUCTION_CLIENT_URI}
      PRODUCTION_API_URI: ${PRODUCTION_API_URI}
      PG_PROD_CONNECTION_STRING: ${PG_PROD_CONNECTION_STRING}
      POSTMARK_API_TOKEN: ${POSTMARK_API_TOKEN}
      REDIS_EXTERIOR_PORT: ${REDIS_EXTERIOR_PORT}
      REDIS_PASS: ${REDIS_PASS}
    ports:
      - "${VIRTUAL_PORT}:${VIRTUAL_PORT}"

networks:
  default:
    external:
      name: ${NETWORK}
